import "..//globals.css";

export const metadata = {
  title: "sm system : Login | Signup",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      {children}
    </div>
  );
}
